import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <div className={styles.main}>
                    {/* Wrapper */}
                    <div className="bg-white rounded-xl shadow-2xl flex-col w-1/4 max-w-md py-6 px-12 relative w-full flex justify-center">

                        {/* Anmelden Section */}
                        <div className="p-8 text-3xl text-indigo-600 font-semibold mb-2 group relative w-full flex justify-center">Anmelden</div>

                        {/* Input Felder */}
                        <div className="flex flex-col items-center pl-6 pr-6">
                            <div className="bg-white mb-4 pb-4 group w-full flex-col justify-center">

                                {/* Nutzername Feld */}
                                <label htmlFor="description" className="block text-xs font-medium text-indigo-900">Nutzername</label>
                                <div className="mt-1 relative rounded-xl text-black pb-4">
                                    <input type="text" name="nutzername" id="nutzername"
                                           className="bg-white focus:border-indigo-500 block w-full py-2 px-4 sm:text-sm rounded-md border-2 border-indigo-900 outline-none"
                                           placeholder="" />
                                </div>

                                {/* Nutzername Feld */}
                                <label htmlFor="description" className="block text-xs font-medium text-indigo-900">Passwort</label>
                                <div className="mt-1 relative rounded-xl shadow-sm text-black">
                                    <input type="password" name="password" id="password"
                                           className="bg-white focus:border-indigo-500 block w-full py-2 px-4 sm:text-sm rounded-md border-2 border-indigo-900 outline-none"
                                           placeholder="" />
                                </div>

                                {/* Checkbox und Passwort vergessen */}
                                <div className="flex mb-2 mt-5 justify-between">
                                    <label className="flex items-center text-xs">
                                        <input type="checkbox" name="merken" className="hover:cursor-pointer mr-2" />Daten merken
                                    </label>
                                    <a href="#" className="text-xs focus:text-indigo-600">Passwort vergessen?</a>
                                </div>
                            </div>
                        </div>

                        {/* Anmelden Button */}
                        <div className="mb-12 pl-6 pr-6">
                            <button type="submit" className="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 hover:shadow-md focus: focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                                Anmelden
                            </button>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    )
}
